services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/share/nginx/html
    ports:
      - "8081:80"

  php:
    image: php:8.3-fpm
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp
